-- Historical one-off script: deleted a specific unbalanced transaction by
-- temporarily disabling a validation trigger.
--
-- Phase 1 single-source-of-truth goal:
--   Production schema (including triggers) must only be changed through
--   Supabase migrations, not ad-hoc ALTER TABLE statements.
--
-- This script is retained as an example of what NOT to do in the future.
-- It MUST NOT be run as-is. If you need to adjust validation behavior,
-- create a migration (e.g., to relax a constraint or add a guard) and
-- then delete or fix specific data using targeted DML.
--
-- Suggested approach for future issues:
--   1) Add a migration that hardens/relaxes the constraint or trigger.
--   2) Write a separate data-fix migration or script that deletes/repairs
--      bad rows without disabling triggers for arbitrary time.

