-- Historical emergency patch: attempted to fix ownerships triggers
-- by replacing them with no-op versions to avoid recursion.
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ may change
--   trigger definitions and ownerships total-fields behavior.
--
-- This script is retained for context and MUST NOT be used to apply
-- schema changes. The desired behavior for ownership total fields is
-- described in:
--   docs/architecture/ownerships-total-fields-implementation.md
-- and the current canonical implementation is encoded in migrations
-- (e.g. 20250911090000_061_integrity_enforcements.sql and neighbours).
--
-- If ownership triggers need to change again, add a new migration that
-- updates the functions/triggers in a controlled, reviewable way.

