-- Deprecated remote patch: Phase 1 lease model core (enums, columns, helper
-- tables, aggregate functions).
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ should own lease
--   schema, helper tables, and functions.
--
-- This file is retained for historical context only and MUST NOT be used
-- to apply schema changes. Lease-related schema and functions are now
-- fully expressed in Supabase migrations. Add new migrations for any
-- future lease model changes.

