-- Deprecated remote patch: integrity constraints/guards for leases, rent_schedules,
-- transaction totals, and related triggers.
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ should define or
--   modify integrity constraints and triggers.
--
-- This file is retained for historical context only and MUST NOT be used
-- to apply schema changes. Refer to the integrity-focused migrations
-- (e.g. 20250911090000_061_integrity_enforcements.sql and related files)
-- for the canonical implementation. New changes should be made via new
-- migrations, not ad-hoc patches.

