-- Deprecated remote patch: fn_create_lease_full and related helper logic.
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ should define
--   or change database functions used by the application.
--
-- This file is retained for historical context only and MUST NOT be used
-- to apply schema changes. The canonical implementation of lease creation
-- functions now lives in the lease-focused migrations (e.g. 20250919000003_108_*
-- and neighbours). Future changes should be made via new migrations.

