-- Deprecated remote patch: unified files/file_links RLS policies.
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ should update
--   RLS and permissions for files/file_links.
--
-- This file is retained for historical context only and MUST NOT be used
-- to apply schema changes. See the files/unified storage migrations
-- (starting at 20251008120000_001_files_unified_schema.sql) for the
-- canonical implementation.

