-- Deprecated reconciliation_log remote patch.
--
-- Phase 1 objective is to ensure only Supabase migrations change schema.
-- The authoritative reconciliation_log DDL is captured in:
--   supabase/migrations/20250912000001_069_reconciliation_log_buildium.sql
--
-- This file remains as documentation only and MUST NOT be used to apply
-- schema changes. If you need to create or modify reconciliation_log,
-- add a new migration instead.

-- Optional sanity check (read-only):
-- select column_name, data_type
-- from information_schema.columns
-- where table_schema = 'public' and table_name = 'reconciliation_log'
-- order by ordinal_position;
