-- Deprecated remote patch: Buildium webhook dead-letter fields, indexes,
-- and dashboard helper view.
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ should add or
--   modify webhook schema, indexes, or views.
--
-- This file is retained for historical context only and MUST NOT be used
-- to apply schema changes. Webhook dead-letter support is now maintained
-- via migrations; add new migrations for future changes.

