-- Deprecated remote patch: add 'Onetime' (and related) enum variants for
-- rent cycle/recurring billing.
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ should update
--   enum types like rent_cycle_enum.
--
-- This file is retained for historical context only and MUST NOT be used
-- to apply schema changes. See migration 20250919000000_105_add_onetime_to_rent_cycle_enum.sql
-- and related files for the canonical enum definition.

