-- Deprecated remote patch: lock lease data model (enum definitions, tables
-- such as rent_schedules/recurring_transactions/lease_documents, and
-- storage bucket wiring).
--
-- Phase 1 single-source-of-truth goal:
--   Only Supabase migrations under supabase/migrations/ should define
--   the canonical lease schema and related enums/tables.
--
-- This file is retained for historical context only and MUST NOT be used
-- to apply schema changes. Refer to the lease-related migrations for the
-- canonical definitions. For new work, create a new migration instead
-- of applying ad-hoc SQL.

