"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
exports.Constants = void 0;
exports.Constants = {
    public: {
        Enums: {
            accounting_basis_enum: ["Accrual", "Cash"],
            appliance_service_type_enum: [
                "Maintenance",
                "Repair",
                "Replacement",
                "Installation",
                "Inspection",
                "Other",
            ],
            appliance_type_enum: [
                "Refrigerator",
                "Freezer",
                "Stove",
                "Microwave",
                "Dishwasher",
                "Washer/Dryer",
            ],
            approval_state_enum: [
                "draft",
                "pending_approval",
                "approved",
                "rejected",
                "voided",
            ],
            assignment_level: ["Property Level", "Unit Level"],
            assignment_level_enum: ["Building", "Unit"],
            automation_frequency_enum: [
                "monthly",
                "quarterly",
                "annually",
                "on_event",
                "weekly",
                "biweekly",
            ],
            automation_rule_type_enum: [
                "recurring_task",
                "recurring_charge",
                "workflow_trigger",
            ],
            bank_account_type_enum: [
                "checking",
                "savings",
                "money_market",
                "certificate_of_deposit",
            ],
            bank_entry_status_enum: ["uncleared", "cleared", "reconciled"],
            bathroom_enum: [
                "1",
                "1.5",
                "2",
                "2.5",
                "3",
                "3.5",
                "4+",
                "4.5",
                "5",
                "5+",
            ],
            bedroom_enum: ["Studio", "1", "2", "3", "4", "5+", "6", "7", "8", "9+"],
            bill_administration_option: [
                "Property Tax",
                "Building Charges",
                "Insurance",
                "Utilities",
                "Other",
            ],
            billing_basis_enum: [
                "per_property",
                "per_unit",
                "percent_rent",
                "job_cost",
                "hourly",
                "one_time",
            ],
            billing_frequency_enum: [
                "Annual",
                "Monthly",
                "monthly",
                "annually",
                "one_time",
                "per_event",
                "per_job",
                "quarterly",
            ],
            buildium_bank_account_type: [
                "Checking",
                "Savings",
                "MoneyMarket",
                "CertificateOfDeposit",
            ],
            buildium_bill_status: [
                "Pending",
                "Paid",
                "Overdue",
                "Cancelled",
                "PartiallyPaid",
            ],
            buildium_lease_contact_role: ["Tenant", "Cosigner", "Guarantor"],
            buildium_lease_status: ["Future", "Active", "Past", "Cancelled"],
            buildium_payment_method: [
                "Check",
                "Cash",
                "CreditCard",
                "BankTransfer",
                "OnlinePayment",
            ],
            buildium_property_type: ["Rental", "Association", "Commercial"],
            buildium_sync_status_type: [
                "pending",
                "syncing",
                "synced",
                "failed",
                "conflict",
            ],
            buildium_task_priority: ["Low", "Medium", "High", "Critical"],
            buildium_task_status: [
                "Open",
                "InProgress",
                "Completed",
                "Cancelled",
                "OnHold",
            ],
            buildium_unit_type: [
                "Apartment",
                "Condo",
                "House",
                "Townhouse",
                "Office",
                "Retail",
                "Warehouse",
                "Other",
            ],
            buildium_vendor_category: [
                "Contractor",
                "Maintenance",
                "Utilities",
                "Insurance",
                "Legal",
                "Accounting",
                "Marketing",
                "Other",
            ],
            buildium_webhook_event_type: [
                "PropertyCreated",
                "PropertyUpdated",
                "PropertyDeleted",
                "UnitCreated",
                "UnitUpdated",
                "UnitDeleted",
                "OwnerCreated",
                "OwnerUpdated",
                "OwnerDeleted",
                "LeaseCreated",
                "LeaseUpdated",
                "LeaseDeleted",
                "BillCreated",
                "BillUpdated",
                "BillPaid",
                "TaskCreated",
                "TaskUpdated",
                "TaskCompleted",
            ],
            charge_status_enum: ["open", "partial", "paid", "cancelled"],
            charge_type_enum: ["rent", "late_fee", "utility", "other"],
            compliance_applies_to: ["property", "asset", "both"],
            compliance_asset_type: [
                "elevator",
                "boiler",
                "facade",
                "gas_piping",
                "sprinkler",
                "generic",
                "other",
            ],
            compliance_event_type: [
                "inspection",
                "filing",
                "correction",
                "violation_clearance",
            ],
            compliance_item_source: [
                "manual",
                "dob_sync",
                "hpd_sync",
                "fdny_sync",
                "open_data_sync",
            ],
            compliance_item_status: [
                "not_started",
                "scheduled",
                "in_progress",
                "inspected",
                "filed",
                "accepted",
                "accepted_with_defects",
                "failed",
                "overdue",
                "closed",
            ],
            compliance_jurisdiction: [
                "NYC_DOB",
                "NYC_HPD",
                "FDNY",
                "NYC_DEP",
                "OTHER",
            ],
            compliance_violation_agency: ["DOB", "HPD", "FDNY", "DEP", "OTHER"],
            compliance_violation_category: ["violation", "complaint"],
            compliance_violation_status: ["open", "in_progress", "cleared", "closed"],
            compliance_work_order_role: ["primary", "related"],
            countries: [
                "Afghanistan",
                "Albania",
                "Algeria",
                "Andorra",
                "Angola",
                "Antigua and Barbuda",
                "Argentina",
                "Armenia",
                "Australia",
                "Austria",
                "Azerbaijan",
                "Bahamas",
                "Bahrain",
                "Bangladesh",
                "Barbados",
                "Belarus",
                "Belgium",
                "Belize",
                "Benin",
                "Bhutan",
                "Bolivia",
                "Bosnia and Herzegovina",
                "Botswana",
                "Brazil",
                "Brunei",
                "Bulgaria",
                "Burkina Faso",
                "Burundi",
                "Cambodia",
                "Cameroon",
                "Canada",
                "Cape Verde",
                "Central African Republic",
                "Chad",
                "Chile",
                "China",
                "Colombia",
                "Comoros",
                "Congo (Republic of the Congo)",
                "Costa Rica",
                "Croatia",
                "Cuba",
                "Cyprus",
                "Czech Republic (Czechia)",
                "Democratic Republic of the Congo",
                "Denmark",
                "Djibouti",
                "Dominica",
                "Dominican Republic",
                "East Timor (Timor-Leste)",
                "Ecuador",
                "Egypt",
                "El Salvador",
                "Equatorial Guinea",
                "Eritrea",
                "Estonia",
                "Eswatini",
                "Ethiopia",
                "Fiji",
                "Finland",
                "France",
                "Gabon",
                "Gambia",
                "Georgia",
                "Germany",
                "Ghana",
                "Greece",
                "Grenada",
                "Guatemala",
                "Guinea",
                "Guinea-Bissau",
                "Guyana",
                "Haiti",
                "Honduras",
                "Hungary",
                "Iceland",
                "India",
                "Indonesia",
                "Iran",
                "Iraq",
                "Ireland",
                "Israel",
                "Italy",
                "Ivory Coast (Côte d'Ivoire)",
                "Jamaica",
                "Japan",
                "Jordan",
                "Kazakhstan",
                "Kenya",
                "Kiribati",
                "Korea (North Korea)",
                "Korea (South Korea)",
                "Kosovo",
                "Kuwait",
                "Kyrgyzstan",
                "Laos",
                "Latvia",
                "Lebanon",
                "Lesotho",
                "Liberia",
                "Libya",
                "Liechtenstein",
                "Lithuania",
                "Luxembourg",
                "Madagascar",
                "Malawi",
                "Malaysia",
                "Maldives",
                "Mali",
                "Malta",
                "Marshall Islands",
                "Mauritania",
                "Mauritius",
                "Mexico",
                "Micronesia",
                "Moldova",
                "Monaco",
                "Mongolia",
                "Montenegro",
                "Morocco",
                "Mozambique",
                "Myanmar (Burma)",
                "Namibia",
                "Nauru",
                "Nepal",
                "Netherlands",
                "New Zealand",
                "Nicaragua",
                "Niger",
                "Nigeria",
                "North Macedonia",
                "Norway",
                "Oman",
                "Pakistan",
                "Palau",
                "Palestine",
                "Panama",
                "Papua New Guinea",
                "Paraguay",
                "Peru",
                "Philippines",
                "Poland",
                "Portugal",
                "Qatar",
                "Romania",
                "Russia",
                "Rwanda",
                "Saint Kitts and Nevis",
                "Saint Lucia",
                "Saint Vincent and the Grenadines",
                "Samoa",
                "San Marino",
                "São Tomé and Príncipe",
                "Saudi Arabia",
                "Senegal",
                "Serbia",
                "Seychelles",
                "Sierra Leone",
                "Singapore",
                "Slovakia",
                "Slovenia",
                "Solomon Islands",
                "Somalia",
                "South Africa",
                "South Sudan",
                "Spain",
                "Sri Lanka",
                "Sudan",
                "Suriname",
                "Sweden",
                "Switzerland",
                "Syria",
                "Taiwan",
                "Tajikistan",
                "Tanzania",
                "Thailand",
                "Togo",
                "Tonga",
                "Trinidad and Tobago",
                "Tunisia",
                "Turkey",
                "Turkmenistan",
                "Tuvalu",
                "Uganda",
                "Ukraine",
                "United Arab Emirates",
                "United Kingdom",
                "United States",
                "Uruguay",
                "Uzbekistan",
                "Vanuatu",
                "Vatican City (Holy See)",
                "Venezuela",
                "Vietnam",
                "Yemen",
                "Zambia",
                "Zimbabwe",
            ],
            deposit_status_enum: ["posted", "reconciled", "voided"],
            dr_cr_enum: ["DR", "CR"],
            email_template_key: ["monthly_rental_statement"],
            email_template_status: ["active", "inactive", "archived"],
            entity_type_enum: ["Rental", "Company"],
            etf_account_type_enum: ["Checking", "Saving"],
            external_sync_source: ["dob_now", "nyc_open_data", "hpd", "fdny"],
            external_sync_status: ["idle", "running", "error"],
            fee_category_enum: ["plan_fee", "service_fee", "override", "legacy"],
            fee_type_enum: ["Percentage", "Flat Rate"],
            FeeFrequency: ["Monthly", "Annually"],
            FeeType: ["Percentage", "Flat Rate"],
            files_entity_type_enum: [
                "Properties",
                "Units",
                "Leases",
                "Tenants",
                "Rental Owners",
                "Associations",
                "Association Owners",
                "Association Units",
                "Ownership Accounts",
                "Accounts",
                "Vendors",
            ],
            gl_category: [
                "receivable",
                "prepayment",
                "deposit",
                "income",
                "expense",
                "other",
            ],
            inspection_status_enum: ["Scheduled", "Completed"],
            inspection_type_enum: ["Periodic", "Move-In", "Move-Out"],
            lease_contact_role_enum: ["Tenant", "Cosigner", "Guarantor"],
            lease_contact_status_enum: ["Future", "Active", "Past"],
            management_fee_type_enum: ["percentage", "flat"],
            monthly_log_stage: [
                "charges",
                "payments",
                "bills",
                "escrow",
                "management_fees",
                "owner_statements",
                "owner_distributions",
            ],
            monthly_log_status: ["pending", "complete"],
            onboarding_status_enum: [
                "IN_PROGRESS",
                "PENDING_APPROVAL",
                "OVERDUE",
                "COMPLETED",
            ],
            onboarding_task_status_enum: [
                "PENDING",
                "IN_PROGRESS",
                "BLOCKED",
                "DONE",
            ],
            payment_intent_state_enum: [
                "created",
                "submitted",
                "pending",
                "authorized",
                "settled",
                "failed",
            ],
            payment_method_enum: [
                "Check",
                "Cash",
                "MoneyOrder",
                "CashierCheck",
                "DirectDeposit",
                "CreditCard",
                "ElectronicPayment",
            ],
            plan_amount_type: ["flat", "percent"],
            plan_percent_basis: ["lease_rent_amount", "collected_rent"],
            property_status: ["Active", "Inactive"],
            property_type_enum: [
                "Condo",
                "Co-op",
                "Condop",
                "Rental Building",
                "Townhouse",
                "Mult-Family",
            ],
            receivable_status_enum: ["open", "partial", "paid", "cancelled"],
            receivable_type_enum: ["rent", "fee", "utility", "other"],
            rent_basis_enum: ["scheduled", "billed", "collected"],
            rent_cycle_enum: [
                "Monthly",
                "Weekly",
                "Every2Weeks",
                "Quarterly",
                "Yearly",
                "Every2Months",
                "Daily",
                "Every6Months",
                "OneTime",
            ],
            rent_schedule_status: ["Past", "Current", "Future"],
            service_plan_enum: ["Full", "Basic", "A-la-carte", "Custom"],
            ServicePlan: ["Full", "Basic", "A-la-carte"],
            staff_role: [
                "PROPERTY_MANAGER",
                "ASSISTANT_PROPERTY_MANAGER",
                "MAINTENANCE_COORDINATOR",
                "ACCOUNTANT",
                "ADMINISTRATOR",
            ],
            staff_roles: [
                "Property Manager",
                "Bookkeeper",
                "Assistant Property Manager",
                "Maintenance Coordinator",
                "Accountant",
                "Administrator",
            ],
            sync_source_enum: ["local", "buildium"],
            task_kind_enum: ["owner", "resident", "contact", "todo", "other"],
            task_source_enum: ["buildium", "manual", "monthly_log"],
            tax_payer_type: ["SSN", "EIN"],
            transaction_status_enum: [
                "",
                "Overdue",
                "Due",
                "Partially paid",
                "Paid",
                "Cancelled",
            ],
            transaction_type_enum: [
                "Bill",
                "Charge",
                "Credit",
                "Payment",
                "JournalEntry",
                "Check",
                "Refund",
                "ApplyDeposit",
                "ElectronicFundsTransfer",
                "Other",
                "Deposit",
                "GeneralJournalEntry",
                "OwnerContribution",
                "ReversePayment",
                "ReverseElectronicFundsTransfer",
                "VendorCredit",
                "RentalApplicationFeePayment",
                "ReverseRentalApplicationFeePayment",
                "ReverseOwnerContribution",
                "VendorRefund",
                "UnreversedPayment",
                "UnreversedElectronicFundsTransfer",
                "UnreversedOwnerContribution",
                "UnreversedRentalApplicationFeePayment",
                "ReversedEftRefund",
            ],
            trust_account_warning_enum: ["Off", "ByProperty", "ByRentalOwner"],
            txn_type_enum: ["Charge", "Payment", "Adjustment", "Refund"],
            unit_status_enum: ["Occupied", "Vacant", "Inactive"],
        },
    },
};
