name: Dependency Scanning

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main]
  schedule:
    - cron: '0 6 * * 1' # Weekly, Mondays 06:00 UTC

permissions:
  contents: read
  security-events: write

jobs:
  npm-audit:
    name: npm audit (prod, high+)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: '18'
          cache: 'npm'
      - name: Install dependencies
        run: npm ci
      - name: Run npm audit (omit dev)
        run: npm audit --omit=dev --audit-level=high

  osv-scanner:
    name: OSV Scanner (high+)
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4
      - name: Scan with OSV-Scanner
        uses: google/osv-scanner-action@v1.1.3
        with:
          scan-args: |
            -r .
          fail-on-severity: HIGH
